version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    networks:
      - voice_network

  backend:
    build:
      context: ./backend
    ports:
      - "5009:5009"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/recognition_app
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_refresh_jwt_secret
    networks:
      - voice_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - voice_network

  db:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recognition_app
    networks:
      - voice_network

networks:
  voice_network:
    driver: bridge